include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = QuickAppLauncherPrefs

QuickAppLauncherPrefs_FILES = QALRootListController.m
QuickAppLauncherPrefs_FRAMEWORKS = UIKit
QuickAppLauncherPrefs_PRIVATE_FRAMEWORKS = Preferences
QuickAppLauncherPrefs_INSTALL_PATH = /Library/PreferenceBundles
QuickAppLauncherPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk